### PR TITLE
Webpack dev server settings fixing

### PR DESCRIPTION
**Pull request by usulpro**
Hello, I tryed to start dev server but it not working (maybe because I work under windows?)
So here some small changes wich helped me to run it

### CODE REVIEW

**Comment by usulpro** [comment]
And the last commit is for using inline style for main scrollarea div

**Comment by BosNaufal** [comment]
Thank you for the pull request! it's awesome~ :grin:  
But something that I don't know is, why we should add inline style while the props for className has existed?

**Comment by usulpro** [comment]
I wanted to make it in a separate pull request, but it went together. So it just for flexibility. Due to that REACT supports both variants of styling as inline or via css and it's so easy to implement. For somebody it may be convenient to use one or the other option, besides, they can be used together (for example if u use some scrollareas in one page)

**Comment by BosNaufal** [comment]
Got it! Thank you so much for your contributions @UsulPro. I'm waiting for your collaboration in next open source project :grin:

**Comment by usulpro** [comment]
Oh sure. Thank you :smile: 
And do you have plans to develop this project? I would have participated, because I like it and I want to use it in my work

**Comment by BosNaufal** [comment]
@UsulPro, Please come in :grin: I would like to thank to you! 
I'll appreciate any contributions to this project~ :+1:

**Pull request merged**
