### PR TITLE
replaces React.PropTypes with `prop-types` from npm package

### PR DESCRIPTION
**Pull request by big-kahuna-burger**
to be compatible with react v16, 15.6.2 warns on accessing React.PropTypes

### CODE REVIEW

**Comment by jasonrhaddix** [comment]
Can we get this merged? Having this issue on v16.

**Comment by jwilliams-ecometrica** [comment]
I would also like this merged please :)

**Comment by padsbanger** [comment]
Merge this please :)

**Comment by synchromatik** [comment]
Is this project abandoned? PR is open from October last year.

**Comment by usulpro** [comment]
It seems that the author has lost interest in this project. If there is a community desired to revive this and join the maintaining team we would kindly ask @BosNaufal to transfer the ownership of repo and add [me](https://www.npmjs.com/~usulpro) as a maintainer to npm package. (I'd offer to create a separate organization and invite developers interested in this). 
I made some effort to upgrade this project some time ago and would be happy to see it in demand now. So I'd help with organizing it but I can't do anything without a few team members who would like to maintain this project. If there are such enthusiastic people let me know, please

**Pull request closed without merging**
